meson.build
Newer versions have breaking changes and aren't yet supported.
=> Changed wlroots dependency version to 0.12

.github/workflows/main.yml, config/viv_config.h, meson.build, meson_options.txt, src/viv_background.c, src/viv_bar.c, src/viv_server.c, src/vivarium.c
This lets the CI check that we don't accidentally introduce segfaults etc., especially on exit which is easier to miss during development.
=> Add build option to run in headless mode and exit immediately

config/viv_config.h, src/viv_server.c
Vivarium with the default config currently crashes on systems other than mine due to non-robust handling of the config loading and the fact that the config includes a default xkb keymap that nobody else has. This fixes that.
=> Make default config run without needing any special environment

src/viv_layout.c
Layout functions should always have ignored floating views, but this was broken during recent layout changes.
=> Make layout functions skip floating views

src/viv_render.c
Borders were erroneously not being drawn due to a logic error in a
recent commit
=> Fix xwayland window border drawing logic

src/viv_server.c
Fixes a segfault if mod+click outside any views.
=> Make cursor always passthrough when not clicking a view

meson.build
Fixes #44 
The wlroots 0.12.0 examples are outdated for the latest versions of dependencies, which is already a problem on Arch linux. There's actually no need to build the examples, so just skipping them by default should be fine.
=> Don't build wlroots examples if building from subproject

include/viv_types.h, src/viv_wlr_surface_tree.c
Fixes #58 - this pointer dereference typo totally messes up the offset used for damage tracking.
=> Fix bug with wlr_subsurface offset not being applied

src/viv_xdg_popup.c
Child popups were broken by #66 - I missed a place where the output needed to be set!
Another strike in favour of properly passing necessary arguments to init, instead of doing it ad-hoc.
=> Make child popups inherit output from their parent

include/viv_types.h, src/viv_cursor.c, src/viv_ipc.c, src/viv_layer_view.c, src/viv_output.c, src/viv_server.c, src/viv_view.c, src/viv_xdg_popup.c, src/viv_xdg_shell.c
Currently vivarium mostly crashes on output destroy as it doesn't remotely clean up properly. Let's fix that.
Fixes #30
=> Properly clear up outputs when destroyed

src/viv_xwayland_shell.c
Currently we don't handle well the case where current size and min size are zero, but a size hint is provided.
=> Make xwayland surface size respect any of size/size_hint/min_size

include/viv_server.h, src/viv_cursor.c, src/viv_server.c, src/viv_xdg_shell.c, src/viv_xwayland_shell.c
This fixes a crash as the grab state currently continues to reference the view. This solution isn't that neat, but it will be easier to tidy it up once seats are properly abstracted in #71
=> Clear server grab state if grabbed view is unmapped

src/viv_server.c
Previously the view-under-cursor algorithm didn't consider the active view before other
views in the layout, leading to focusing the wrong view as layouts always draw the active
view on top.
=> Make view-under-cursor detection match view draw order

config/config.toml, config/viv_config.h, include/viv_config_types.h, src/viv_input.c, src/viv_toml_config.c, tests/test_config.c
Adds the possibility to configure disabling the input device while typing and
allows for choosing the click method. Both of which are useful for touchpads
----
Two points to consider:
1. I wasn't sure if the way I set the default values is within expectations or not;
2. I couldn't figure out how to run the tests.
=> Additional input options

include/viv_types.h, protocols/meson.build, protocols/xml/wlr-output-power-management-unstable-v1.xml, src/meson.build, src/viv_server.c
Introduces support for the wlr_output_power_management_v1 protocol,
which allows for compatibility with power saving/dpms tools and utilities
----
I couldn't find a way to turn off my laptop's screen without closing the lid, so I implemented this.
An easy way to test is with `wlopm` (https://sr.ht/~leon_plickat/wlopm/) or a patched version of swaylock (https://github.com/gartnera/swaylock)
=> Support for wlr_output_power_management_v1

src/viv_view.c, src/viv_xwayland_shell.c
This is by no means an ideal fix, but it should at least resolve an easily-triggered crash when leaving a workspace in between view init and map. I think this has particularly affected xwayland popups as they can appear/disappear a lot and often seem to have a long enough display between init and map for the user to perform actions.
Also created #95 to track that the target box handling isn't neat and needs a little rethink.
=> Work around target box failure if a workspace's output is NULL

include/viv_types.h, protocols/meson.build, protocols/xml/idle.xml, src/meson.build, src/viv_seat.c, src/viv_server.c
Implements support for the idle protocol, so that vivarium is compatible with
tools such as swayidle
----
Another simple one from my wishlist. I essentially looked at how sway first implemented this for inspiration. I left out cursor frame events as the description suggests it never happens in isolation. 
An easy way to test is to run `swayidle` with a low timeout:
e.g. `swayidle timeout 3 xeyes resume fire timeout 6 pcmanfm`
Then check that `xeyes` runs after 3 seconds of inactivity, that `fire` runs after activity is resumed, and that `pcmanfm` is run after 6 seconds.
=> idle protocol

src/viv_view.c
- If the workspace ends up empty, focus is now removed;
- Otherwise, focus is passed onto the next view
----
This addresses some issues I have been having where the focus ends up on unexpected views
There is some overlap with the `fullscreen` PR, but the merge/rebase should be trivial
=> Fix refocusing when shifting views to other workspaces

src/viv_xwayland_shell.c
This addresses a bug introduced in the fullscreen PR. I forgot to check if `size_hints` is not `NULL` before accessing it. A real world implication of this is that Steam would make vivarium crash when you tried to browse the library. 
Fixes #107
=> xwayland: only access size_hints if it's not NULL

include/viv_server.h, include/viv_types.h, src/viv_server.c, src/viv_workspace.c
Introduces support for the idle inhibit protocol (idle-inhibit-unstable-v1).
According to the protocol description, visible surfaces can prevent displays
from entering the idle state.  The introduced code supports xdg, xwayland,
and layer surfaces.  Though, in practice, this is limited to what wlroots
signals (i.e. no xwayland)
----
I have been using this with no issues so far.
An easy way to test is to fire up swayidle with a low timeout:
`swayidle timeout 5 xeyes`
Make sure it's working.
Then launch `mpv`, make sure it doesn't go idle.
Then move `mpv` to another workspace, make sure it goes idle.
Then switch to that workspace, make sure it doesn't go idle.
Then move it back, ensure it does.
Then switch back, ensure it doesn't.
Then close it, ensure it does.
I am open to alternatives to …
=> Idle inhibit protocol

config/config.toml, config/viv_config.h, include/viv_config_types.h, src/viv_input.c, src/viv_toml_config.c
Resolves #116 
As pointed out by @flaviozavan on #116, tap to click simply wasn't configured by vivarium. That's an omission on my part, I thought I'd caught the minimal set of libinput functionality to cover this kind of common configuration but apparently not.
This PR adds a config option to enable tap to click as well as to make the basic left-right-middle or left-middle-right config choice.
=> Add tap to click config support

include/viv_types.h, src/viv_seat.c, src/viv_server.c
Implements the primary selection protocol
Also functions as a workaround for this annoying firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1731511
This can be tested by trying to copy across different views using the middle mouse button. Firefox issue can be tested by trying to copy straight from the address bar into another app using any method, without the workaround, it is only able to paste onto Firefox itself.
=> Primary selection protocol

include/viv_types.h, src/viv_xwayland_shell.c
Explicitly handle xwayland configures. This fixes issues seen in darktable and prusa-slicer, where surfaces would never be mapped
----
To test, try running prusa-slicer or darktable without the proposed changes. Darktable never maps a single surface, while prusa-slicer will only map the splash screen. Apply changes, and they both should work as expected.
=> Handle xwayland configures

include/viv_seat.h, include/viv_types.h, include/viv_view.h, include/viv_workspace.h, src/viv_cursor.c, src/viv_layer_view.c, src/viv_output.c, src/viv_seat.c, src/viv_view.c, src/viv_workspace.c, src/viv_xdg_shell.c, src/viv_xwayland_shell.c
- Centralizes the keyboard focus workflow, so that it happens through a single function, where we can ensure the focus dance follows all steps. This addresses bugs including #114;
- Makes it so xwayland surfaces can be deactivated. This fixes bugs when, for example, using Slack, where notifications would automatically be consumed, and the status would always be set to available;
- Touches up mouse focusing on workspace switch #88.
I've been using this daily, and it seems stable and correct.
=> Ensure focus consistency

include/viv_config_types.h, src/viv_input.c, src/viv_toml_config.c
I saw this request on IRC and though it would be a good way to get started with hacking on vivarium. This pull request adds config options for libinput’s different acceleration modes and speed.
=> Add pointer acceleration config support

include/viv_types.h, src/viv_server.c
Enable wlroot’s gamma control protocol to support redshift-like applications.
=> Gamma control protocol

src/viv_seat.c
Ensures keyboard notification enter events are only sent to valid keyboards. Null values could be seen when focus was changed using the mouse after unplugging a keyboard.
----
To test:
1. Use keyboard;
2. Open 2 views;
3. Focus one of them;
4. Unplug keyboard that was last used;
5. Click the other view;
6. Watch segfault before this change, or no segfault with it.
=> Ensure keyboard is not NULL before sending enter notification
